// Généré automatiquement

export const generatedRoutes: string[] = [
  "/spectacles/chapitres-de-la-chute-saga-des-lehman-brothers",
  "/spectacles/quand-viendra-la-vague",
  "/spectacles/les-enfants-du-rhone",
  "/spectacles/dans-le-decor-de",
  "/spectacles/gnocchi-a-meyrin",
  "/spectacles/smoke",
  "/spectacles/madame-de",
  "/spectacles/queer-crip-becoming",
  "/spectacles/disperses",
  "/spectacles/murer-la-peur",
  "/spectacles/fa-m-ille",
  "/spectacles/dans-le-decor-de-fa-m-ille",
  "/spectacles/choc-la-friandise-des-dieux",
  "/spectacles/gnocchi-a-plainpalais",
  "/spectacles/dans-le-decor-de-choc",
  "/spectacles/la-grosse-deprime",
  "/spectacles/quasimodo-aux-miroirs",
  "/spectacles/time-to-relax-une-introduction-a-la-performance-relax",
  "/spectacles/gnocchi-a-bellevue",
  "/spectacles/au-bout-de-la-laisse",
  "/infos-pratiques",
  "/infos-pratiques/billetterie",
  "/infos-pratiques/equipe",
  "/pour-les-ecoles",
  "/pour-les-artistes",
  "/pour-les-artistes/technique",
  "/pour-les-artistes/bureau-des-compagnies",
  "/accessibilite",
  "/ateliers-theatre",
  "/demain"
];